### ISSUE TITLE
[Jest27] Cannot add a hook after tests have started running. Hooks must be defined synchronously. 

### ISSUE THREAD

**Issue by kopax-polyconseil** [Codecademy/console-fail-test#64] opened 2021-06-09 12:50 UTC
I was forced to update my test dependencies and it seems the module `console-fail-test` cannot work anymore:

```
    Cannot add a hook after tests have started running. Hooks must be defined synchronously.

      32 |   server.listen()
      33 |   // eslint-disable-next-line @typescript-eslint/no-unsafe-call
    > 34 |   consoleFailTestModule.cft({
         |                         ^
      35 |     testFramework: 'jest',
      36 |     spyLibrary: 'jest',
      37 |     console: allowConsoleRuntimeConfig,
```

Any clue how we can fix this?

**Comment by kopax-polyconseil** [comment] 2021-06-23 08:41
@codecademydev @codecaaron any chance to get some opinion about this one ? This was one of the coolest tool in our test utils.

**Comment by JoshuaKGoldberg** [comment] 2021-06-23 11:52
Hey @kopax-polyconseil sorry for the delay, this slipped through the cracks!

It's hard to diagnose without a working repro and we don't reproduce the issue in our tests. Do you have a project we could take a look at?

**Comment by JoshuaKGoldberg** [comment] 2021-08-21 15:08
Ping @kopax-polyconseil - I still can't reproduce this. Is there some sample code you could send?

**Comment by JoshuaKGoldberg** [comment] 2021-09-15 14:22
Closing as aged away. To anybody reading: if you see this again, please do post back with info and we can re-open!

**Closed by JoshuaKGoldberg** 2021-09-15 14:22 UTC
Labels: needs more info

**Comment by kopax-polyconseil** [comment] 2022-07-26 14:35
hello @JoshuaKGoldberg , sorry for the delay, I never got the notification of your reply.

We have a project here https://github.com/pass-culture/pass-culture-app-native/pull/3306 with the issue, but basically, you should be able to reproduce just by configuring jest as we did for cft, in our setupTest.js
